### ISSUE TITLE
Group and Validators

### ISSUE THREAD

**Issue by miili** [Maillol/aiohttp-pydantic#34]
`Group` does not respect `@validators`.

**Comment by Maillol** [comment]
Could you more explain your issue please? Send me a minimal code example that reproduce your issue and tell me what do you expect.

**Comment by branyan12** [comment]
Hi everyone
I have a problem and need help, how can i import seismic data (.mseed) trace and stations to seismic_data.pkl and then use the imported one in BEAT. Does anyone have experience with this? Please guide me.
Kind Regards.
