### ISSUE TITLE
Optional body parameters

### ISSUE THREAD

**Issue by crazyscientist** [Maillol/aiohttp-pydantic#51]
The README describes how query parameters are optional and how default values can be set.

It might be up for debate, whether this is a good idea, but here it goes:

It would be nice, if it were possible to declare body parameters as optional, too, and provide default values.

---

If you don't like this idea, it would be nice on the other hand, if there were an error.

Currently, if one tries this, one only gets the default values in a dictionary; independent of what the request body contains.

---

To illustrate this situation, I have prepared a little script: 
https://gist.github.com/crazyscientist/2358f59bed61273c82ef583abb64e2f9

**Comment by Maillol** [comment]
I tried your little script,

`typing.Optional[T]` means `T | None`. 

We cannot accept two possible type as body

The good way is: 

```python
@routes.post("/demo1")
class Demo1View(PydanticView):
    async def post(self, /, params: ParamModel) -> r201[ParamModel]:
        return web.json_response(data=params.model_dump(), status=201)
```

If you want aiohttp-pydantic returns a 400 if extra parameters is added. Use the pydantic feature:
 
```python
from pydantic import BaseModel, Extra

class ParamModel(BaseModel):
    debug: bool = False
    verbose: bool = False
    force: bool = False

    class Config:
        extra = Extra.forbid
```

https://docs.pydantic.dev/latest/errors/validation_errors/#extra_forbidden

**Comment by Maillol** [comment]
Contribution are welcome !
