### ISSUE TITLE
How to declare list body parameter for POST request

### ISSUE THREAD

**Issue by tonal** [Maillol/aiohttp-pydantic#67]
How to declare list body parameter for POST request?

Example 1
```python
class ViewPost1(PydanticView):
  async def post(self, ids:list[int])  -> r200[list[int]]:
    return ids
```

Example 2
```python

class Items(BaseModel):
  uid: UUID
  name:str
  count: int

class ViewPost2(PydanticView):
  async def post(self, items:list[Items])  -> r200[int]:
    return sum(it.count for it in items)
```

**Comment by tonal** [comment]
I try reimplplemented **PydanticView.parse_func_signature** but **generate_oas** not handled that.

```python
class ViewPost1(PydanticView):
  @staticmethod
  def parse_func_signature(func: Callable) -> Iterable[AbstractInjector]:
    path_args, body_args, qs_args, header_args, defaults = _parse_func_signature(func)

    for name, annot in tuple(qs_args.items()):
      if name == 'items':
        del qs_args[name]
        body_args[name] = _TypeAdapter4Getter(annot)
        if defval.default is ...:
          del defaults[name]
        else:
          defaults[name] = defaults[name].default
    # ... code of original PydanticView.parse_func_signature


class _TypeAdapter4Getter:
  ta:TypeAdapter
  def __init__(self, annot):
    self.ta = TypeAdapter(annot)

  def model_json_schema(self) -> dict:
    return self.ta.json_schema()

  def model_validate(self, value: Any) -> Any:
    return self.ta.validate_python(value)
```
Maybe **_parse_func_signature** add as static method to **PydanticView**?

**Comment by tonal** [comment]
Or you can do as in FastApi and add label classes to explicitly specify the source of the parameter:

```python
class ViewPost1(PydanticView):
  async def post(self, ids:list[int]=InBody(...))  -> r200[list[int]]:
    ...
```

```python
class ViewPost2(PydanticView):
  async def post(self, items:Annotated[list[items], InBody()])  -> r200[list[int]]:
    ...
```
The advantages of this method are declarative.
In addition, additional data can be specified in the label classes - for example, a description, an obsolete attribute, and etc.

**Comment by Maillol** [comment]
You can use pydantic RootModel

https://docs.pydantic.dev/latest/concepts/models/#rootmodel-and-custom-root-types


```
from pydantic import RootModel

class Item(BaseModel):
    uid: UUID
    name: str
    count: int


Items = RootModel[list[Item]]

class ViewPost2(PydanticView):
    async def post(self, items: Items) -> r200[int]:
        return web.json_response({"count": sum(it.count for it in items.root)})
```

**Comment by Maillol** [comment]
> I try reimplplemented **PydanticView.parse_func_signature** but **generate_oas** not handled that.

In fact use or redefine PydanticView.parse_func_signature is deprecated. The `PydanticView` and `decorator.inject_params` will have a unique entry point to use custom  `parse_func_signature` in the next version

But currently this entry point to use custom `parse_func_signature` does not exist.
You can try to monkey path `aiohttp_pydantic.injectors._parse_func_signature`.
